site_name: Документация XenForo 2
site_description: Документация разработчика для XenForo 2
site_author: Hkr32
site_favicon: xenforo-favicon.png

theme:
  name: readthedocs
  language: ru
custom_dir: xf2
extra_css:
  - 'https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap'
  - 'extra.css'

nav:
- Обзор:
  - Начало работы: index.md
- Site Administrators (or common):
  - Template syntax: template-syntax.md
  - REST API: rest-api.md
- Developers:
  - Add-on structure: add-on-structure.md
  - Development tools: development-tools.md
  - General concepts: general-concepts.md
  - Routing basics: routing-basics.md
  - Controller basics: controller-basics.md
  - Entities, finders, and repositories: entities-finders-repositories.md
  - Criteria: criteria.md
  - Managing the schema: managing-the-schema.md
  - Let's build an add-on: lets-build-an-add-on.md
- Designers:
  - Designing styles: designing-styles.md
  - Template syntax: template-syntax.md
- Appendix(es):
    - macOS Dev Environment: macos-dev.md
    - Linux Dev Environment: linux-dev.md
    - Windows Dev Environment: windows-dev.md
    - Visual Studio Code and Xdebug: vscode.md
    - Scotch Box: scotchbox.md

repo_url: https://github.com/xenforo-ru/docs/
edit_uri: edit/main-ru/docs/

markdown_extensions:
  - admonition
  - toc:
      permalink: 

copyright: <a href="https://xenforo.com/" target="_blank">Документация разработчика для XenForo&reg; 2.x &copy;2010-2021 XenForo Ltd.</a>
